### ISSUE TITLE
Resource group for VSI data volumes

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/terraform-ibm-landing-zone-vsi#504]
### Description

Currently the data volumes created by the module are provisioned in Default resource group, ignoring the VSI RG and not allowing to specify one for the data volume.

The module should use the resource group provided in VSI attributes or support a resource_group in data volume structure.

### New or affected modules

- storage.tf - ibm_is_volume resource should use var.resource_group_id or RG provided in the storage volume variable structure.
- variables.tf - if resource_group attribute is added to block_storage_volumes structure

---

**Comment by ocofaigh** [comment]
@in-1911 Jordan has created a [PR](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/pull/507) with a proposed solution. Can you confirm this will resolve your issue?

**Comment by in-1911** [comment]
@ocofaigh - you are showing a boot volume. Those were fine before.
It's the data volume that was always created in Default. 
What you would need to test is deploy a VSI with an additional **data volume** using v2.4.4, upgrade the module and try to apply again. I think terraform will try to drop and re-create the data volume in that case.

**Comment by ocofaigh** [comment]
@in-1911 ahhh yes you are right. I was able to reproduce by passing a value into the `block_storage_volumes` variable. By default this variable value is an empty list. And as expected, when I attempt to upgrade, terraform wants to recreate. The best I can do is update the release notes with this information, but also update the example that runs as part of our tests to deploy an additional data volume. 

Can you confirm that you are also deploying an additional data volume using the [terraform-ibm-landing-zone](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone) too? Are you doing this as part of the override.json? Would it be possible to share the json config?

**Comment by ocofaigh** [comment]
FYI, release notes have been updated in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/releases/tag/v2.5.0

**Comment by in-1911** [comment]
Yes, I am using the VPC Landing Zone deployable architecture component.
The VSI is configured via override.json (or rather the override parameter in the project configuration).
The whole config is rather large, the relevant VSI config is fairly straightforward (I skipped the remaining VSI attributes like SG, SSH key, etc):

```json
{
.....
  "vsi": [
    {
        "boot_volume_encryption_key_name": "PREFIX-vsi-volume-key",
        "image_name": "ibm-redhat-8-6-minimal-amd64-5",
        "machine_type": "cx2-8x16",
        "name": "sbx-workload",
        "resource_group": "PREFIX-workload-rg",
        "block_storage_volumes": [
            {
                "name":           "datavol",
                "profile":        "general-purpose",
                "capacity":       100,
                "encryption_key": "PREFIX-vsi-volume-key"
            }
        ]
....
    }
  ]
....
}
  
```
