### ISSUE TITLE
Can we get floating_ip_id in output along with the floating_ip

### ISSUE THREAD

**Issue by nupurg-ibm** [terraform-ibm-modules/terraform-ibm-landing-zone-vsi#597]
### Description

Here https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/blob/e2a7498975dfa7ae72ee4e1cca950f442c586f53/outputs.tf#L34 Can we get floating_ip_id as well in the output along with the floating_ip

**Comment by nupurg-ibm** [comment]
Thanks!
Can we get these two attributes with "list" output map also?
Seems like both output maps are giving consistent values for now.

**Comment by toddgiguere** [comment]
Same properties above have also been added to full VSI map and released: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/releases/tag/v3.2.1
