### ISSUE TITLE
Error while creating network load balancer member

### ISSUE THREAD

**Issue by gerdwatmann** [terraform-ibm-modules/terraform-ibm-landing-zone-vsi#649]
### Affected modules

* terraform-ibm-landing-zone-vsi

### Terraform CLI and Terraform provider versions

* Terraform version: Terraform v1.5.7
* Provider version: registry.terraform.io/ibm-cloud/ibm v1.63.0

### Terraform output

[terraform_outout.txt](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/files/14854084/terraform_outout.txt)

### Expected behavior

NLB Load Balancer Backend Pool should be attached with the generated VSIs from the module.

### Actual behavior

terraform apply fails with above attached message:
"code": "member_invalid_nlb_target",
"message": "Network load balancer members must be specified with either id or href or crn."

### Steps to reproduce (including links and screen captures)

Using this terraform configuration during terraform apply.
[vsi_terraform.txt](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/files/14854124/vsi_terraform.txt)

### Anything else

Any suggestions appreciated. Thanks!
---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by maheshwarishikha** [comment]
Fix has been provided and available in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/releases/tag/v3.3.0

Thanks.
