### ISSUE TITLE
[terraform-ibm-landing-zone-vsi] Unable to create multiple VSIs per subnet due to VNI name not being unique

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-landing-zone-vsi#750]
Reported by consumer:

> While working with 4.3.0 version of landing-zone-vsi, I understand we create VNI for every VSI by default. And I saw the created VNI name is just based on the subnet name. So if I am creating two VSI's under the same subnet, on the second VNI creation I am getting this issue:
> ```
> ╷
> │ Error: CreateVirtualNetworkInterfaceWithContext failed Provided Name (nprdpvn-hpc-bastion-subnet-0-vni) is not unique
> │ {
> │   "StatusCode": 409,
> ```
> In my opinion, VNI names should contain something other than subnet names so that they can be unique for same subnet as well.

**Comment by ocofaigh** [comment]
Update:

> The error isn't due to using more than 1 vsi per subnet, that works.
> In this specific case we have two different module block using the same subnets, so the vsi map created will have the same key and the same vni name.

**Comment by Aashiq-J** [comment]
PR merged. Closing issue.
